version: "3.1"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    ports:
      - 3306:3306
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
